#="================================================================================================================"
#connection-timeout-seconds="10"
#connection-uri="postgresql://postgres@localhost:5432/rstudio?sslmode=verify-full&sslcert=/etc/ssl/certs/postgresql/postgresql.crt&sslkey=/etc/ssl/certs/cacert/postgresql/postgresql.key&sslrootcert=/etc/ssl/certs/cacert/postgresql/root.crt&options=-csearch_path=public"
#database="rstudio"
#directory="/var/lib/rstudio-server"
#host="localhost"
#password="postgres"
#port="5432"
#provider="sqlite"
#username="postgres"
auto-create="1"
