# Server Configuration File

# The server user here must match the server user configured in launcher.conf.
server-user=rstudio-server

# Launcher Configuration
# The launcher-address here is the address of the Launcher server relative to the Workbench server.
launcher-address=localhost

# The launcher-port configured here must match the port configured in launcher.conf.
launcher-port=5559

# The launcher-sessions-callback-address is the address that sessions started through the Launcher
# use to contact Workbench. For a single-node Workbench installation with the Local Launcher
# Plugin, and not using SSL (the default configuration), localhost should suffice.
# If you set the rserver's www-port, or ssl-enabled, you must update this address to match.
#
# For more information about configuring this correctly in more complex environments, see this
# section of the admin guide:
# https://docs.rstudio.com/ide/server-pro/job_launcher/configuration.html
launcher-sessions-callback-address=http://localhost:8787

launcher-default-cluster=Local
launcher-use-ssl=0
launcher-sessions-enabled=1

# Enable "pluggable auth module" support so sessions can leverage PAM for local account provisioning
# when the user logs in. 
auth-pam-sessions-enabled=1

# Set to 1 to turn on load balancing (requires a shared postgres database config)
load-balancing-enabled=0

# Set the default Python package index to Posit Public Package Manager for pip and uv
session-python-index-url=https://packagemanager.posit.co/pypi/latest/simple
